server:
  port: 9527
spring:
  application:
    name: AIGou-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
   plat.serviceId: aigou-plat-service
   plat.path: /plat/**
   product.serviceId: aigou-product-service
   product.path: /product/**
   common.serviceId: aigou-common #这是调用满足条件的服务名，注意要小写
   common.path: /common/** #这是所有路径前的通配
  ignored-services: "*"
  prefix: "/services"